---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: local-accounts
    image: rockylinux:9
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    prepare: prepare.yml
scenario:
  name: default
verifier:
  name: testinfra
